import pandas as pd

df = pd.read_excel('Bao cao TTKT - Mau - Main.xlsm',sheet_name='import TMS QDTTKT QDXL')
print(df)
# Gộp dữ liệu theo mã số thuế và số Q.Định
grouped_df = df.groupby(['Mã số thuế', 'Số Q.Định'], as_index=False).agg({
    'CQT': 'first',
    'Tên NNT': 'first',
    'Loại QĐ': 'first',
    'LT': 'first',
    'Tên loại thuế': 'first',
    'Từ kỳ': 'first',
    'Đến kỳ': 'first',
    'Lý do t.tra/k.tra': 'first',
    'Tạo bởi': 'first',
    'Mã TH': 'first',
    'Người TĐ cuối': 'first',
    'Ng T.Hiệń': 'first',
    'T.Nhiệm': 'first',
    'TT Hồ sơ': 'first',
    'TT.Xử Lý': 'first',
    'TT.XLý HS': 'first',
    'Giả': 'first',
    'T.cNgoài': 'first',
    'Tiêu đề': 'first',
    'Diễn Giải.': 'first',
    'Ưu tiên': 'first',
    'Leo thang': 'first',
    'Loại': 'first',
    'Mô tả NN': 'first',
    'Khóa tình huống kỹthuật': 'first',
    'HS': 'first',
    'Ng.Đóng': 'first',
    'Leo thang1': 'first',
    'Loại1': 'first',
    'Ưu tiên': 'first',
    'Cấp p.q': 'first',
    'DS t.thái': 'first',
    'SystmStat.': 'first',
    'ObjectGUID': 'first',
    'Sys.Status': 'first',
    'UserStatus': 'first',
    'Bộ x.lý': 'first',
    'Trnhiệm': 'first',
    'CQ ra QĐ': 'first',
    'Ngày QĐ': 'first',
    'Ngày c.bố': 'first',
    'Ngày K/L': 'first',
    'Thời gian tạo': 'first',
    'Thay đổi': 'first',
    'NgàyĐóng': 'first',
    'Hoàn tất': 'first',
})
print(grouped_df)
#STT		Mã số thuế			Số Q.Định			 		Người TĐ cuối	Ng T.Hiệń	T.Nhiệm	TT Hồ sơ	TT.Xử Lý	TT.XLý HS	Giả	T.cNgoài	Tiêu đề	Diễn Giải.	Ưu tiên	Leo thang	Loại	Mô tả NN	Khóa tình huống kỹthuật	HS	Ng.Đóng	Leo thang	Loại	Ưu tiên	Cấp p.q	DS t.thái	SystmStat.	ObjectGUID	Sys.Status	UserStatus	Bộ x.lý	Trnhiệm	CQ ra QĐ	Ngày QĐ	Ngày c.bố	Ngày K/L	Thời gian tạo	Thay đổi	NgàyĐóng	Hoàn tất
